package temple

var coreFuncs = map[string]interface{}{
	"elapsed":        Elapsed,
	"duration":       Duration,
	"inNanoSeconds":  InNanoSeconds,
	"inMicroSeconds": InMicroSeconds,
	"inMiliSeconds":  InMiliSeconds,
	"inSeconds":      InSeconds,
	"inMinutes":      InMinutes,
	"inHours":        InHours,
	"inDays":         InDays,
	"inBytes":        InBytes,
	"inKBytes":       InKBytes,
	"inMBytes":       InMBytes,
	"inGBytes":       InGBytes,
	"inTBytes":       InTBytes,
	"inPBytes":       InPBytes,
	"inCount":        InCount,
	"inKCount":       InKCount,
	"inMCount":       InMCount,
	"inGCount":       InGCount,
	"inTCount":       InTCount,
	"inPCount":       InPCount,
}
